- BESM6/besm6_cpu.c
- BESM6/besm6_defs.h
- BESM6/besm6_panel.c
> BESM6: Implemented SET CPU PANEL/NOPANEL.

- BESM6/besm6_cpu.c
- BESM6/besm6_defs.h
- BESM6/besm6_mmu.c
- BESM6/besm6_panel.c
- BESM6/besm6_sys.c
- BESM6/besm6_tty.c
smoothed front panel lights, corrected a typo in besm6_tty.c
> BESM6: Implemented hardwired front panel programs,

- BESM6/besm6_cpu.c
- BESM6/besm6_panel.c
- BESM6/besm6_printer.c
- BESM6/besm6_punch.c
No warnings in BESM6/*.c with -Wall
> BESM6: Enhanced the front panel, code cleanup.

- AltairZ80/s100_mdsad.c
The source file to be updated provides emulation of the North Star DD
floppy disk controller. The proposed change steps the head only when the
step bit in the order byte transitions from 1 to 0. This is the way the
actual hardware functions. Previously, the emulation would step any time
an order was issued and the step bit was 1. This behavior caused some
original software (e.g., Lifeboat CP/M 2.2) to end up on an incorrect
track.
> AltairZ80: Fix head stepping to only occur on 1 to 0 transitions

- PDP11/pdp11_dmc.c
These changes cure a number of issues in RSTS/E, which is more
sensitive to details of emulation than most:
1. Additional KMC opcodes supported for ROMI
2. MCLR now initializes the CSRs per the spec
3. MCLR and ROMI are processed immediately at CSR write rather than
being deferred, because these actions are implemented in the device
hardware rather than in the microprogram.
> PDP10, PDP11, VAX: Make DMC/DMR initialization more accurate.

- BESM6/besm6_cpu.c
- BESM6/besm6_tty.c
Is this better?
Thanks, I keep forgetting about "push -f".
> BESM6: Improved TTY I/O (responsiveness, variable rate, turbo/authentic)

- B5500/b5500_cpu.c
- B5500/b5500_urec.c
- sim_card.c
- sim_card.h
Cleaned up support for binary cards to sim_card, also added architecture description to head of B5500_cpu.c
> Updates to Sim_card and B5500

- 3B2/3b2_defs.h
- 3B2/3b2_sysdev.c
- 3B2/3b2_sysdev.h
- 3B2/README.md
Improves the Time-of-Day clock calculations.
> 3b2: Improve TOD calculation

- 3B2/3b2_cpu.c
- 3B2/3b2_iu.c
- 3B2/3b2_sysdev.c
> 3b2: Coverity issue cleanup

- 3B2/3b2_dmac.c
- 3B2/3b2_iu.c
- 3B2/3b2_iu.h
- 3B2/3b2_sys.c
Initial support for second on-board serial port
> 3b2: Initial CONTTY support

- I7000/i7000_com.c
Added in attributions for original code.
> I7000: Updated copyright notice on i7000_com.c.

- display/display.c
Probably one of those "just one more edit before I commit/push" mistakes.
Sorry!
> DISPLAY: remove duplicate end of block comment oops

- 3B2/3b2_cpu.c
- 3B2/3b2_cpu.h
- 3B2/3b2_sys.c
- 3B2/3b2_sys.h
Symbolic memory examination was severely broken. This change fixes it.
> 3b2: Fix fprint_sym_m

- 3B2/3b2_cpu.c
Clean up compiler warnings on Windows and OS X
> 3b2: Fix compiler warnings

- 3B2/3b2_if.c
This change fixes a critical floppy booting issue.
> 3b2: Tighten floppy timing

- PDP11/pdp11_rom.c
- PDP11/pdp11_sys.c
- makefile
This is a ROM device for booting from the VT11 card in a GT40.
I'm posting this for review.  This is in very raw form.  If this approach is OK, I'll rework it as necessary for inclusion in SIMH.
> PDP11: ROM device.

- AltairZ80/altairz80_hdsk.c
Fixes #662. Note also that the updated version of https://schorn.ch/cpm/zip/cpm2.zip is needed.
> AltairZ80: Fixed hard disk device boot

- AltairZ80/wd179x.c
Should fix CID 1477048:  Memory - illegal accesses  (OVERRUN)
> AltairZ80: Make WD179X device more robust and fix Coverity issue

- 3B2/3b2_cpu.c
- 3B2/3b2_defs.h
- 3B2/3b2_if.c
- 3B2/3b2_io.c
- 3B2/3b2_io.h
- 3B2/3b2_mmu.h
- 3B2/3b2_ni.c
- 3B2/3b2_ni.h
- 3B2/3b2_ports.c
- 3B2/3b2_sys.c
- Visual Studio Projects/3B2.vcproj
- makefile
Implements an Ethernet device ("NI", for "Network Interface") for the 3B2 simulator.
> 3b2: NI 10Base5 Ethernet Device

- VAX/is1000_defs.h
- VAX/vax410_defs.h
- VAX/vax420_defs.h
- VAX/vax43_defs.h
- VAX/vax440_defs.h
- VAX/vax_xs.c
> VAX420: Fix for LANCE when system memory > 16MB

- VAX/is1000_sysdev.c
- VAX/vax410_sysdev.c
- VAX/vax420_sysdev.c
- VAX/vax43_sysdev.c
- VAX/vax43_syslist.c
- VAX/vax440_defs.h
- VAX/vax440_sysdev.c
- VAX/vax4xx_rz94.c
- Memory sizing for VAX440
- DMA address mapping for VAX440
- Modifiers table for RZ94
- Further naming corrections
> VAX4xx: Multiple fixes

- 3B2/3b2_cpu.c
This change adds a small infinite loop program that will be used by the simulator to establish a reasonable guess at the host's performance in order to precalibrate the system timer.
> 3b2: Provide precalibration program

- display/type340.c
See here: https://github.com/simh/simh/pull/720#issuecomment-509915223
> Fix unbalanced comment in type340.c

- 3B2/3b2_cpu.c
- 3B2/3b2_ni.c
- 3B2/3b2_ni.h
This change implements asynchronous (non-polling) mode for NI Ethernet packet receive.
> 3b2: Improve NI performance

- README.md
- appveyor.yml
I'm experimenting with AppVeyor to add Windows continuous integration to SIMH.
> Visual Studio CI build

- sim_video.c
- sim_video.h
As discussed in https://github.com/rcornwell/sims/pull/179
> VIDEO: Add support for SDL2 game controllers

- sim_card.c
Fixed minor error in sim_card.c with Binary card image format cards.
> CARD: Clean up typo from Coverity fix.

- B5500/b5500_cpu.c
- PDP10/kx10_cpu.c
- PDP10/kx10_mt.c
- PDP10/kx10_tu.c
Update B5500 and KA10 register definitions.
> Update register definitions.

- PDP10/kl10_nia.c
- PDP10/kx10_cpu.c
- PDP10/kx10_imp.c
Removed PACK references, add polling to NIA if async eth fails.
Cleaned up some extended addressing instruction errors.
> KA10: Minor code fixes.

- PDP11/pdp11_ch.c
- PDP11/pdp11_daz.c
- PDP11/pdp11_ng.c
- display/ng.h
Work in progress.  Feel free to comment though.
> PDP11: Fix register definitions.

- PDP11/pdp11_ch.c
- display/ng.c
1. Shifting a negative value.
2. size_t converted to uint16.
> Fix some warnings.

- imlac/imlac_dp.c
The Imlac display processor would only allow one single level of subroutine calls.  An option expanded this to an eight level stack.  This is needed by the Maze game.
> IMLAC: Implement 8-level return stack for display processor.

- Visual Studio Projects/imlac.vcproj
- imlac/imlac_bel.c
- imlac/imlac_sys.c
- makefile
A hardware device particular to MIT with some kind of bell sound.
> IMLAC: Add MIT bell.

- B5500/b5500_urec.c
- I7000/i7000_cdp.c
- I7000/i7000_dsk.c
- I7000/i7000_lpr.c
- I7000/i7000_mt.c
- I7000/i7090_cdp.c
- I7000/i7090_cpu.c
- I7000/i7090_lpr.c
- PDP10/ka10_iii.c
- PDP10/ka10_pclk.c
- PDP10/kl10_fe.c
- PDP10/kx10_cp.c
- PDP10/kx10_cpu.c
- PDP10/kx10_defs.h
- PDP10/kx10_lp.c
- PDP10/kx10_pt.c
- PDP10/kx10_sys.c
- Visual Studio Projects/PDP10-KA.vcproj
- makefile
Update B5500 and I7000 and PDP10 output only devices to default to append mode.
PDP10-KA: various fixes for WAITS support. New TOD device for WAITS.
> Regular update.

- imlac/imlac_cpu.c
- imlac/imlac_dp.c
- imlac/imlac_pt.c
- Implement CPU instruction execution history.
- Load "block" register when loading DPC.
Added:
- Remove unused variable.
> IMLAC: Three updates.

- B5500/b5500_urec.c
- I7000/i7000_cdp.c
- I7000/i7000_lpr.c
- I7000/i7090_cdp.c
- I7000/i7090_lpr.c
- PDP10/kx10_cp.c
- PDP10/kx10_cpu.c
- PDP10/kx10_pt.c
> Regular updates.

- sim_card.c
- sim_card.h
Documentation for raw formats.
> CARD: Updated comments on raw and other special formats.

- imlac/imlac_cpu.c
- imlac/imlac_dp.c
Minor updates for better debugging.
> IMLAC: Improve debug output.

- tt2500/tt2500_key.c
- tt2500/tt2500_uart.c
The previous commit had some untested last-minute changes.
> TT2500: Fix unit flags.

- .github/workflows/build.yml
- .travis.yml
- .travis/deps.sh
Continuous integration build using GitHub Actions.  See https://github.com/features/actions
> CI: Build using GitHub Actions.

- AltairZ80/s100_hdc1001.c
The ADC HDC-1001 in SIMH was incomplete and non-functional.
Finish the simulation to be functional under CP/M 2.2, CP/M 3.0,
and OASIS 5.6.
> AltairZ80: HDC-1001: Complete the implementation.

- makefile
> allow .git to be a file or directory to handle submodules

- AltairZ80/vfdhd.c
> AltairZ80: vfdhd: Fix unit detach.

- PDP11/pdp11_vt.c
Use `SET VT KEYBOARD=SWITCHES` or `NOSWITCHES` to enable/disable toggling switches with the keyboard.  Default is `SWITCHES`.
Resolves #1001.
> PDP11: New VT11 setting to enable/disable switches.

- PDP11/pdp11_ng.c
> PDP11: Use MATCH_CMD to match comand strings.

- AltairZ80/s100_mdsad.c
The North Star MDS-AD disk controller supports both single- and
double-density operation.  While mixed-density is supported by the
controller, it is not supported by AltairZ80 due to a limitation of the
.nsi image file format.  The .nsi image file format requires all sectors
to be of the same density.
> AltairZ80: Add MDS-AD support for single-density

- sim_video.c
> VIDEO: Fix use of uninitialized variable.

- sim_video.c
Sometimes an SDL event is reported with windowID = 0 which is not a match to any window SIMH has opened.  Both @Isysxp and I have seen this.  I have no explanation for why this happens, but ignoring those events seem harmless.
I will produce a pull request that fixes this.
> video: unrecognized windowID

- AltairZ80/wd179x.c
@psco, @markpizz : FYI, this adds support for the WD1795 / 1797 side select output.
> wd179x: Add support for wd1795/7 side select output.

- AltairZ80/wd179x.c
- AltairZ80/wd179x.h
> wd179x: Keep WD179X_INFO_PUB in sync.

- sim_video.c
The handling of vid_dst_last and vid_data_last was not updated to work with multiple windows, which can cause window updates to be lost.
I'm posting this draft which fixes the problem by adding a new vid_vptr_last to keep track of the latest window making an update.  I'm not sure if this is preferable, or of each window should maintain their own vid_dst and data_last information.
> VIDEO: Fix bug in vid_dst_last handling.

- 3B2/3b2_if.c
This commit fixes an issue that caused 3B2 floppy diagnostics to fail if the floppy drive unit was not attached. The 3B2 floppy controller has a "force interrupt" command that should run whether or not the floppy unit is attached to an image.
> 3b2: Allow force interrupt if not attached

- sim_imd.c
> sim_imd: Resolve coverity issues.

- PDP10/ks10_uba.c
- PDP10/kx10_cpu.c
> KA10: Fixed BLTUB/BLTBU instructions.

- AltairZ80/altairz80_cpu.c
- AltairZ80/s100_hdc1001.c
> AltairZ80: Resolve CID 1514796,1514860, 1514861.

- imlac/imlac_pt.c
- tt2500/tt2500_cpu.c
Coverity found three issues.  This fixes two of them.
> TT2500, IMLAC: Fix two Coverity issues.

- PDP10/kx10_cpu.c
> KA10: Cleanup some extended addressing issues with KL10B.

- sim_imd.c
> sim_imd: Resolve CID 1502448, 1502460.

- PDP10/kl10_fe.c
- PDP10/kx10_cpu.c
Can these be merged in as two commits.
> KA10: Minor updates.

- sigma/sigma_rad.c
sigma_rad.c SENSE and Write orders did not set write protect status correctly.
> sigma_rad:fix wp test in sense and write op

- sigma/sigma_io.c
- sigma/sigma_io_defs.h
sigma: Implement CM (Chaining Modifier) flag to IOP simulation in sigma_io.c
> sigma: Add chaining modifier flag to io

- sim_timer.c
> Appveyor test to avoid saving results

- AltairZ80/altairz80_cpu.c
Adds the ability to mark pages as ROM when loading Intel HEX files.
> AltairZ80: Adds "ROM" option to "load -h"

- AltairZ80/altairz80_cpu.c
The previous PR that added the "ROM" option to "load -h" did not support extended memory. @psco provided an update that corrects the problem.
> AltairZ80: Updates prev PR to support Extended Mem

- sigma/sigma_mt.c
Implemented the Attention device interrupt in response to the -A switch on an attach request.  This is support for the CP-V Automatic Volume Recognition (AVR) feature.
> sigma: implement attention interrupt to sigma)mt.c
