simh/simh

- SAGE/m68k_cpu.c
Commit a9ac7c153 properly avoided writing past the end of cache_line,
but in doing so introduced an error as to the first memory address that
should be written. This fix avoids writing past the cache_line by simply
reading the previous memory location.
Fixes the CP/M 68K simulation example and issue #181
> Fix off-by-one in reading cache address from memory

- SDS/sds_cpu.c
- SDS/sds_defs.h
- SDS/sds_sys.c
1. In sim_instr, if an Unauthorized Memory Access trap occurs, the code was enforcing the 940 Reference Manual's admonition that:
"The instruction in the trap location must be a MARK PLACE AND BRANCH (BRM) instruction."
Normally there is a BRM TRAPM in location 041, but when exploring a memory trap, the TSS monitor code at CEX (SMEM) temporarily puts a BRU CEX2+1 in location 041.
Clearly the hardware allows BRU in the trap transfer vector, because the system uses that feature. Change simulator to allow BRM or BRU in Unauthorized Memory Access Trap vector word in location 041.
2. Page 17 of the 940 reference manual specifies special actions when the target address of a BRU, BRX, BRM or BRR instruction cannot be accessed because it's not in the memory map. The simulator was not doing this, …
> SDS: Corrections to memory trap logic

- SDS/sds_cpu.c
Improper implementation of the OVT and OTO instructions. OV is always zero or one, so the Boolean AND in the  original if statement would always fail. Also, these instructions are supposed to skip if overflow is not set, the opposite of the way it was coded.
> SDS: Fix overflow test instructions OVT and OTO

- SDS/sds_stddev.c
The simulator stops when reading past EOF on the paper tape device's attached disk file (or if no file is attached to this device). The SDS timesharing system is capable of processing an end-of-record interrupt in these circumstances, resulting in proper error reporting to the user program that is reading paper tape.
> SDS: Do not stop simulator on paper tape reader error

- SDS/sds_mux.c
When stuffing the LOGOUT command to a pseudo-teletype, the command script processing program CCP encountered a race condition because the MUX timing was too slow.  The pseudo-teletype did not reliably log off as desired. Cutting the event wait time in half fixed the problem.
> SDS: Adjust communication MUX inter-character timing

- AltairZ80/mfdc.c
Do not insert the computed checksum for VGI disk images, since the
checksum is already present in the sector data.
> AltairZ80: mfdc: allow disk controller to work with MZOS disk images

- makefile
cygwin now includes development packages for the SDL2 and SDL video
libraries (libSDL2-devel and libSDL-devel). Adjust makefile to find the
libSDL2.dll.a or libSDL.dll.a library.
> makefile: cygwin build video support using SDL2 (preferred) or SDL

- AltairZ80/altairz80_sys.c
- AltairZ80/s100_mdsa.c
- makefile
The first disk controller made by North Star was a single density
controller (MDSA). This was followed by the double density controller
(MDSAD) that is already supported in SIMH. This update adds support for
the single density controller as device MDSA. Since the controllers are
not software compatible, this update allows running of older software
designed for the MDSA controller.
> AltairZ80: Add support for North Star single density controller

- slirp_glue/qemu/qemu-common.h
Compilation under Cygwin was giving the warning
slirp/slirp.h:24:0: warning: "O_BINARY" redefined
^
In file included from /usr/include/sys/fcntl.h:3:0,
from /usr/include/fcntl.h:15,
from slirp_glue/qemu/osdep.h:57,
from slirp_glue/qemu/qemu-common.h:15,
from slirp/slirp.c:24:
/usr/include/sys/_default_fcntl.h:56:0: note: this is the location of
the previous definition
#define O_BINARY _FBINARY
> slirp_glue: cleanup compiler warning for redefinition of O_BINARY

- BESM6/besm6_arith.c
Multiplying a negative number by a zero value with a non-zero exponent produced wrong results.
> BESM6: Fixed a bug in multiplication.

- PDP11/pdp11_rf.c
I found this while playing with the V3 RSTS tapes on Bitsavers, which are for RF system disk.
> PDP11: Fix setting of CSR address in RF11 boot command.

- PDP11/pdp11_cpu.c
Only changed the address of MMR3 in a comment.  No actual code changes.
> PDP11: Correct the address of MMR3 in a comment

- 3B2/3b2_sysdev.c
- 3B2/3b2_sysdev.h
- This change adds support for storing time between boots in the Time
of Day clock. An effort has been made to keep the Time of Day clock
in sync with the wall clock between boots, so that user-set time
advances properly between boots.
- Added a couple of custom help routines for TOD and NVRAM.
I will be filling in more help routines as time permits.
> 3b2: Time of Day Clock

- 3B2/3b2_cpu.c
- An overflow bug was causing INSFW and EXTFW to fail
on Windows hosts compiled with Microsoft Visual Studio.
This commit fixes the issue and causes 3B2 diagnostics
to pass under win32.
> 3b2: Fix overflow of mask bits in INSFW/EXTFW

- 3B2/3b2_cpu.c
- 3B2/3b2_defs.h
- 3B2/3b2_id.c
- 3B2/3b2_id.h
- 3B2/3b2_iu.c
This commit improves the integrated disk (ID) controller's behavior,
enabling full support for up to two 72MB (emulated WREN II)
integrated winchester disks.
> 3b2: Support for multiple integrated disks

- 3B2/3b2_defs.h
- 3B2/3b2_iu.c
- 3B2/3b2_iu.h
- 3B2/3b2_mmu.h
- 3B2/3b2_sys.c
Two commits:
1. Soft power-off, providing support for the emulator to power itself off via a software command, as in the real 3B2/400.
2. Fix for a critical MMU bug that had been lurking undetected for a surprisingly long time, but prevented C-Kermit from being compiled.
> Soft Power-Off and Critical MMU fix

- 3B2/3b2_defs.h
- 3B2/3b2_iu.c
- 3B2/3b2_iu.h
- 3B2/3b2_sysdev.c
Adds modem control line speed configuration to prevent FIFO overflow.
> 3b2: CONTTY line configuration

- 3B2/3b2_defs.h
- 3B2/3b2_if.c
- 3B2/3b2_if.h
- 3B2/3b2_mmu.c
GCC 4.1.2 produced several warnings about inline functions.
This commit fixes those warnings.
> 3b2: Fix warnings generated by older GCC

- 3B2/3b2_cpu.c
- 3B2/3b2_cpu.h
- 3B2/3b2_defs.h
- 3B2/3b2_iu.c
The 3B2 emulator did not have support for traps, rendering debugging
under the simulator fairly useless. This change adds support for
trap handling. The 'sdb' UNIX debugger under SVR3 should now work
correctly.
> 3b2: Allow handling of TRACE and BREAKPOINT traps

- 3B2/3b2_iu.c
- 3B2/3b2_iu.h
The CONTTY emulation now honors parity, baud rate, and character bit
size as set by the operating system.
> 3b2: Allow OS to set baud rate and parity

- 3B2/3b2_cpu.c
- 3B2/3b2_mmu.c
This fix prevents several cases when writing or reading I/O can cause nasty side effects.
> 3b2: Prevent attempts to ex/dep IO

- .travis.yml
- .travis/deps.sh
This install some prerequisite  libraries for the Travis CI build.
For an unknown reason I had to install libegl1-mesa-dev and libgles2-mesa-dev too to make apt happy.
> Install prerequisite libraries for Travis CI.

- 3B2/3b2_cpu.c
- 3B2/3b2_defs.h
- 3B2/3b2_dmac.c
- 3B2/3b2_dmac.h
- 3B2/3b2_id.c
- 3B2/3b2_id.h
- 3B2/3b2_if.c
- 3B2/3b2_if.h
- 3B2/3b2_iu.c
- 3B2/3b2_iu.h
- 3B2/3b2_mmu.c
- 3B2/3b2_sysdev.c
This change is a major refactor of how DMA and the DUART interact.
DMA implementation can now be overridden by individual devices that
require DMA. Disk and Floppy both continue to use a generic DMA
implementation, but the DUART code replaces the generic DMA with its
own implementation that correctly rate-limits TX. Among other things,
this allows the simulator to work correctly with real serial
terminals. This functionality has been tested on an AT&T 5620 "Blit"
terminal, which can run the 'layers' windowing software from the
simulator.
> 3b2: Refactor DUART and DMA

- 3B2/3b2_cpu.c
- 3B2/3b2_cpu.h
- 3B2/3b2_defs.h
- 3B2/3b2_id.c
- 3B2/3b2_if.c
- 3B2/3b2_io.c
- 3B2/3b2_io.h
- 3B2/3b2_iu.c
- 3B2/3b2_sys.c
Adds a skeleton framework for CIO ("Common I/O") feature cards. The
first feature card to be implemented will be the "PORTS" serial MUX.
Part of this support involved reworking IRQ handling in the CPU. It
now respects both IRQ Vector and IPL.
This change also removes all 'assert(0)' calls from the simulator and
replaces them with generic "Simulator Error" halts. These should only
happen if there's a genuine logic error lurking somewhere.
> 3b2: CIO feature card framework

- 3B2/3b2_mmu.c
On a full cache miss, the MMU should only bring a page
descriptor into cache if the segment descriptor does NOT
have the 'contiguous' bit set.
> 3b2: Fix minor MMU paging bug

- display/type340.c
In the lineTwoStep function, a typo makes vectors in two quadrants drawn incorrectly.
CC @philbudne
> display: Fix bug in Type 340 vector drawing routine.

- display/x11.c
If the DISPLAY environment variable isn't set, the ws_init call to XkbSetDetectableAutoRepeat will crash due to a NULL pointer.
> display: Fix X11 crash when DISPLAY unset.

- PDP10/pdp10_defs.h
- PDP10/pdp10_ksio.c
- PDP10/pdp10_sys.c
- PDP11/pdp11_ch.c
- PDP11/pdp11_defs.h
- PDP11/pdp11_io_lib.c
- PDP11/pdp11_sys.c
- VAX/vax730_defs.h
- VAX/vax730_syslist.c
- VAX/vax750_defs.h
- VAX/vax750_syslist.c
- VAX/vax780_defs.h
- VAX/vax780_syslist.c
- VAX/vax860_defs.h
- VAX/vax860_syslist.c
- makefile
The CH11 is a Unibus device which can be used with PDP-11, VAX, and KS10.  It's a network interface for MIT's Chaosnet.
Software that should run on SIMH that supports this device include:
- ITS
- Berkeley Unix with MIT patches
- MINITS, a PDP-11 Chaosnet router/terminal concentrator
Outside SIMH, there's KLH10 and Lisp machine simulators.  Various encapsulating transport mechanisms exist: UDP, IP, Ethernet.
Documentation:  
https://lm-3.github.io/amber.html#Hardware-Programming-Documentation
> Unibus CH11: Chaosnet interface

- PDP11/pdp11_ch.c
> PDP10, PDP11, Unibus VAX: Set CH11 TX done on reset.

- 3B2/3b2_dmac.c
The DMAC controller "Current Word Count" expects to decrement beyond 0 to 0xffff. Its initial value should also be 0xffff. Setting the initial value to 0 introduced a very subtle bug related to DUART self-test following a soft power reset.
> 3b2: Properly initialize DMAC Current Word Count

- display/type340.c
- display/type340.h
I'm not sure if this is appropriate here.  It kind of straddles upstream SIMH (this repo) and @rcornwell's KA10 simulator.
The background is that I want the Type 340 simulation to use sim_ws.c instead of x11.c.  This is because I want the new `vid_display_kb_event_process` API.
To do this, I need to pass the SIMH dptr from the KA10 simulator, to `display_init` which will in turn pass it on to `ws_init`.  The sim_ws `ws_init` expects the dptr instead of the UNIT * passed to the x11 `ws_init`.
There's a corresponding change to the top-level makefile which replaces x11.c with sim_ws.c, but it doesn't make sense for this repository.  There's also a change to ka10_dpy.c of course.
> display: Update 340 simulation to use sim_ws.

- 3B2/3b2_id.c
- 3B2/3b2_if.c
- 3B2/3b2_if.h
- 3B2/README.md
- Formerly, the floppy controller buffered an entire diskette image
in memory using the unit buffer, and flushed it out on detach or
shutdown. This worked well enough, but it's better to have the
device use the SIMH disk sector read and write routines and
behave like a true disk.
- Read Only (Write Protect) logic has also been enabled in the
floppy controller, allowing users to mount images that do not
have write permissions.
- The IF (Integrated Floppy) and ID (Integrated Disk)
device names were poorly chosen. They conflict with built-in
scp commands and mess up the help system. This commit
changes them to IFLOPPY and IDISK, respectively.
NOTE!! THIS IS A BREAKING CONFIG CHANGE!!
> 3b2: Make floppy controller a DEV_DISK device

- makefile
Windows 10 1803 or later NTFS filenames are set to be case-sensitive if the Windows Subsystem for Linux (WSL) feature is turned-on. This was causing a build under cygwin 3.0.1 to fail detecting the libpcap header and library locations in the ../windows-build/winpcap directory.
> makefile: Fix case-sensitive path for cygwin 3 with Windows 10 WSL

- 3B2/3b2_defs.h
- 3B2/3b2_ni.c
- scp.c
- scp.h
- sim_fio.c
This change also addresses some unused function parameter warnings issued by GNU Flycheck (not generally used by the build process, but useful when editing files with Flycheck enabled)
> 3b2: Fix Coverity identified issues

- 3B2/3b2_cpu.c
- 3B2/3b2_sysdev.c
- 3B2/3b2_sysdev.h
This change enables the simulator to be shut down cleanly via a
soft-power shutdown command. This is implemented in the real 3B2/400
through the sanity timer, which, if it reaches zero, sets a bus timeout
flag in the CSR and issues an interrupt at IPL 15. The operating
system (System V UNIX) treats this as a shutdown request and enters
runlevel 0.
To use this change in a SIMH startup script, for example to implement a
3B2 simulator as a service, one could add these commands:
BOOT
SET TIMER SHUTDOWN
CONTINUE
EXIT
On catching a SIGTERM, SIGINT, or SIGHUP, the simulator would return to
SCP control, set the soft power shutdown flag, and then continue
simulator execution. After the system is cleanly shut down, the
simulator would then exit back to the operating system.
> 3b2: Soft-power shutdown via TIMER command

- PDP11/pdp11_xq.c
Correct the MOP data type code for the Device Type field in the SysID
message, and the value used for device type DELQA.
> PDP11: fix SysID message data for LQA

- 3B2/3b2_ni.c
- 3B2/3b2_ni.h
Previously, the NI ethernet device expected to do all
autoconfiguration at attach time. Furthermore, if attaching failed for
some reason (e.g., permission issues on a tap device, etc.) the card
would be left autoconfigured, but in a broken state that could lead to
reading uninitialized memory.
This change fixes those bugs, and allows the device to be attached and
detached more freely. The card is now autoconfigured when it is
enabled.  Attaching and detaching are analogous to connecting or
disconnecting an ethernet transceiver from the physical device.
> 3b2: Correct behavior for NI attach and detach

- VAX/vax820_ka.c
- VAX/vax820_uba.c
As reported in #690
Also:
- Removed some debug messages that were left in from development.
- Renamed some macros to be more consistent with other simulators (xxx_RD would usually be a read mask)
> VAX8200: Added missing error bit to DWBUA CSR

- PDP11/pdp11_cpu.c
Fixes #701.  The issue is more general than just breakpoints, it
potentially affects any exception dealt with by the ABORT macro.
> PDP11: Fix PSW handling for breakpoints and other aborts

- 3B2/3b2_sysdev.c
Fixes a compilation warning in 3b2_sysdev.c caused by a lack of explicit cast from `void *` to `struct timer_ctr *`
> 3b2: Fix for compilation warning

- 3B2/3b2_cpu.c
This is a bug fix for a significant bug in unsigned addition.
Integer addition of unsigned types could fail to set the overflow flag, leading to errors in the SVR3 floating point emulation library that rely on the overflow flag to detect carry out of high bit on unsigned addition. This change will correctly set the V flag if the high bit should be carried out on an add.
> 3b2: unsigned addition overflow

- 3B2/3b2_mau.c
- 3B2/3b2_mau.h
- A bug in the Square Root implementation could lead to
an infinite loop.
- Incorrect rounding was used when MAU destination register
was single or double word.
- Fix Coverity-discovered issues.
> 3b2: Fix critical MAU issues

- 3B2/3b2_mau.c
Fixed several possible loss of precision warnings when implicitly casting t_uint64 to uint32.
> 3b2: Fix Windows build warnings

- 3B2/3b2_cpu.c
STRCPY must increment both source and destination pointers (R0 and R1).
> 3b2: Fix STRCPY instruction

- 3B2/3b2_cpu.c
- 3B2/3b2_ctc.c
- 3B2/3b2_ctc.h
- 3B2/3b2_defs.h
- 3B2/3b2_ni.c
- 3B2/3b2_ni.h
- 3B2/3b2_sys.c
- The previous fix for STRCPY introduced a new bug. STRCPY must always  copy the final NULL terminator of the string, but must NOT increment  the source or destination pointers for the NULL terminator.
- The CTC simulation did not correctly support streaming mode, which can in some cases request reads that are not on 512-byte block boundaries.
- To begin to support System V Release 4 UNIX, the NI card (called EMD under SVR4) needed to support several more CRC codes for pump code.
> 3b2: STRCPY fix, CTC and NI cleanup

- 3B2/3b2_ctc.c
- 3B2/3b2_ctc.h
The CTC (Cartridge Tape Drive) device has two subdevices, "FT25" and "FD5", which were not being set up correctly on initialization. This change fixes that behavior.
> 3b2: Add correct CTC subdevice information

- 3B2/3b2_cpu.c
The WE32100 supports expanded datatypes for its opcodes, allowing an
opcode to override the default size (byte/halfword/word) expected by the
instruction. For example:
CMPH &0x10000,{uword}-8(%fp)
Without the {uword} marker, this instruction would only compare the
lower 2 bytes of -8(%fp) against the lower two bytes of the constant
value 0x10000, since the CMPH instruction compares halfwords. However,
with the {uword} marker, the CMPH instruction promotes the opcode from a
halfword to an unsigned word, sign extending if appropriate.
The CMP{W|H|B} instruction implementation in the 3B2 simulator was
ignoring any expanded type markers on its opcodes when checking whether
to set the "N" (negative) bit in the PSW, leading to a failure in
compiling GCC. This fix causes the instruction to honor …
> 3b2: CMP{W|H|B} instruction fix

- PDP11/pdp11_ng.c
Resolves #750 NG device has too many vectors.  This fix is needed for MIT's SITS operating system.
Also fixes wrong text.
> PDP11: Fix NG bugs.

- PDP8/tests/pdp8_test.ini
The D0AB (PDP-8: Basic Instruction Test 1) stops after just three instructions to let the operator verify that the CLA and HLT instructions works properly. After that the operator is expected to press the CONT switch to continue to the rest of the tests in the diag.
> PDP8: Fix prematurely stopped diag test

- display/display.c
- display/display.h
As per request.
Adds to display.h:
```
extern void display_close(void *dptr); 
```
Used to close a display and associated resources.  Should be called from SIMH device reset routines when DEV_DIS is off.
> display: Add display_close.

- PDP1/pdp1_dpy.c
- PDP11/pdp11_daz.c
When [this KA10 pull request](https://github.com/rcornwell/sims/pull/179) is done, I'd like to do the same for PDP-1 Spacewar and PDP-11 Dazzle Dart.
> PDP-1, PDP-11: USB gamepad/joystick support

- display/display.c
- sim_video.c
If there is more than one display device and they call display_close from their reset routines, they will conflict.  This adds a check that only the device that opened the display is allowed to close it.
The other commit is a cleanup as per SDL documentation.  Maybe it's harmless to initialize and quit both subsystems, but I'd rather err on the side of cautiousness here.
> Display/video fixes.

- makefile
I was alerted to the fact that the 3B2 target was using the wrong include directory variable: `-I ${ATT3B2M400D}` should have been `-I ${ATT3B2D}`. This change corrects the problem.
> makefile: Fix incorrect 3B2 include directory

- 0readme_ethernet.txt
FreeBSD doesn't up the tap interface by default. Work around this by changing the default
> FreeBSD tweak

- imlac/imlac_cpu.c
Instruction decoding used wrong bits.
> IMLAC: Fix bug in shift/rotate instructions.

- imlac/imlac_dp.c
> IMLAC: Fix bug in long vector instruction.

- imlac/imlac_kbd.c
Explicitly call the reset function for the modifier to take effect.
> IMLAC: Fix keyboard TYPE=CONSOLE.

- imlac/imlac_cpu.c
- imlac/imlac_crt.c
Minor fixes for the data switches.
Many Imlac programs require data switch 0 to be on by convention.  Switch 0 is the most significant bit in the data switch register, so type `DEPOSIT DS 100000` to set it.
> IMLAC: Fix data switches.

- imlac/imlac_dp.c
- imlac/imlac_tty.c
- Display PC masked to be inside core memory.
- Do not sign extend characters read from TTY.
> IMLAC: Fix two minor bugs.

- imlac/imlac_kbd.c
- sim_video.c
- sim_video.h
This adds sim_video APIs for querying and setting fullscreen mode.  And then uses these APIs from the Imlac simulator.
When in fullscreen mode, the frame buffer is scaled to the size of the display and positioned in the center.
> IMLAC: Fullscreen mode.

- 3B2/3b2_400_mau.c
Explicitly cast booleans to t_uint64 before doing logical negation.
> 3b2: Fix clang warnings

- NOVA/nova_cpu.c
Problem: Currently when viewing the Nova CPU history the carry flag is always displayed as 0 regardless of it's actual value at the time.
Cause: The carry bit is stored in `bit 17` and is lost when stored into the `int16 carry` member of `struct Hist_entry`
Solution: Shift carry into `bit 0` before storing it in the CPU history. Improve code for displaying carry bit.
> NOVA: Fix carry display in CPU instruction history

- AltairZ80/s100_tarbell.c
The 'tarbell' device now supports Tarbell model 1011 single density
and model 2022 double density floppy disk controllers. The model is
selected using the "SET TARBELL MODEL={SD|DD}" command. Also removed
some unused local variables.
> AltairZ80: Adds support for the Tarbell 2022 double density controller

- scp.c
- sim_video.c
- sim_video.h
I'm working on a simulation of the General Turtle TT2500.  As can be seen below, it had two separate displays: one for text, and another for vector strokes.  I wonder if extending the SIMH video API to multiple displays would be under consideration?
> VIDEO: Support for multiple displays

- imlac/imlac_bel.c
- imlac/imlac_cpu.c
- imlac/imlac_crt.c
- sim_video.c
- sim_video.h
As per https://github.com/simh/simh/pull/965#issuecomment-733172291.
This cleans up *some* uses of #ifdef HAVE_LIBSDL in the Imlac simulator.  The sim_video component offers stubs when SDL isn't available, but the display library doesn't and isn''t even linked in by the makefile.
> VIDEO, IMLAC: Add new sim_video stubs.  Use them in Imlac simulator.

- imlac/imlac_crt.c
- imlac/imlac_kbd.c
Don't open a display window during power-on reset.
Change #ifdefs to USE_DISPLAY.
> IMLAC: Fixes for the display.

- .travis.yml
Older Xcode versions no longer work with Homebrew.  The Travis CI build has been failing for a while, and this fixes that.
> TRAVIS: Update Mac build to use Xcode 12.

- AltairZ80/wd179x.c
- AltairZ80/wd179x.h
- sim_imd.c
- sim_imd.h
The ImageDisk sectsize field was incorrectly set to the number of
bytes in the sector, when it should be an index as follows:
00 =  128 bytes/sector
01 =  256 bytes/sector
02 =  512 bytes/sector
03 = 1024 bytes/sector
04 = 2048 bytes/sector
05 = 4096 bytes/sector
06 = 8192 bytes/sector
Tested disk formatting on MS-DOS 1.25, Cromemco CP/M 2.2,
Cromemco CDOS, OASIS 5.6.
> sim_imd: Properly calculate IMD sectsize.

- PDP11/pdp11_daz.c
Typing F11 toggles the window between fullscreen and window mode.
> PDP11: Toggle NG display fullscreen with F11.

- AltairZ80/s100_mdsad.c
The "Window" bit was getting cleared too late, causing the "next" sector
to be written under North Star DOS.  Due to differences between CP/M and
North Star disk access routines, this was not an issue under CP/M.
Test: Verify that North Star DOS and CP/M can format, copy and verify an
entire disk.
North Star Disk Operating System, Version 2.1.1, at  100
+GO DT 2
SINGLE(S) OR DOUBLE(D) DENSITY TEST? D
BOTH SIDES (Y OR N)? Y
LOAD DISKETTE THEN PRESS RETURN TO BEGIN TEST
PASS COMPLETE
PASS COMPLETE
PASS COMPLETE
PASS COMPLETE
PASS COMPLETE
CONTROL-C STOP
+GO CD 1 2
COPY BOTH SIDES (Y OR N)? Y
LOAD DISKETTES AND PRESS RETURN WHEN READY.
COPY COMPLETED.
+GO CK 1
DISKETTE CHECK, VERSION 1
CHECK CODE: 46513
+GO CK 2
DISKETTE CHECK, VERSION 1
CHECK CODE: 46513
+
> AltairZ80: Fix North Star MDS-AD for NSDOS

- sim_video.c
- sim_video.h
As discussed in https://github.com/simh/simh/pull/935#issuecomment-732132435 and below, here is added support for using the alpha channel in sim_video.
> VIDEO: Allow setting alpha blending mode.

- .github/workflows/build.yml
Following up on @nj7p's commit 96c32fcb80a7bd1f25f81932004de7bb43f4f7e8.
> Intel-Systems: Remove imds and isys build targets from GitHub Actions.

- 3B2/3b2_ports.c
- 3B2/3b2_ports.h
Serial line setup was inadvertantly clobbering the number of lines on initial setup, leading to potential invalid configuration.
> 3B2: Don't clobber number of serial lines

- 3B2/3b2_if.c
The Rev 3 firmware does not check floppy controller status before
commanding a sector read, which can lead to calling sim_disk_rdsect()
on a detached unit. With this checkin, the simulator will no longer
attempt a read or write if the floppy unit is not attached.
> 3B2: Do not read from detached floppy

- H316/h316_udp.c
The H316 has a file called h316_udp.c that implements a transport for an (ARPANET) host-IMP interface.  (Also the IMP-IMP modem links.)  The IMP was the router in the ARPANET.  Each IMP could serve up to four host computers.  So far this has been sitting unused on the IMP side.  I have tested and fixed some problems (#1085, #1087), and now I'm adding the interface to the host side.  At least two of the SIMH emulators have software for connecting to the ARPANET: PDP-10 and PDP-11.
This makes for potentially three copies of the h316_udp.c code.  Would it be possible to lift this to a common file?
> H316: Remove unneeded #include in h316_udp.c.

- sim_serial.c
COM ports greater than COM9 on Windows can only be opened using
the DOS device UNC path \\\\.\\
Prefix the filename passed to CreateFile() with this prefix to
address this issue.
> serial: Support COM ports > COM9 on Windows

- 3B2/3b2_ctc.c
- 3B2/3b2_ports.c
The CTC and PORTS pump code for System V Release 2.0.5 for the 3B2 is
different from the pump code used by SVR 3, leading to PORTS and CTC
diagnostics failing to pass when running SVR2. This change adds
support for the pump code used in SVR 2.
> 3b2: Support for SVR 2.0.5 diagnostics

- PDP10/ks10_cty.c
- PDP10/ks10_kmc.c
- PDP10/ks10_uba.c
- PDP10/kx10_cpu.c
- PDP10/kx10_defs.h
- PDP10/kx10_rh.c
Fixed page fault issue during ILDBP/IDBP.
Set KMC default state to disabled.
> KA10: Fixed bug with page fault during ILDB/IDBP

- BESM6/besm6_disk.c
- BESM6/besm6_tty.c
One of the two parallel interface consoles (TTY26) works in the Videoton-340 mode;
disconnecting a remote TTY session works like powering the terminal down.
After reconnecting, it is necessary to type "HYC" blindly to re-initialize the line.
Added TMXR line reordering.
> BESM6: A Coverity fix, TTY enhancements.

- sim_disk.c
This fixes issue #1106 -- the last sector number reported was
off by one (sector past the last free sector).
> DISK: Fix off by one error in reporting RSTS file structure info

- sim_imd.c
The recent change to check that the IMD file track header record is 5
bytes introduced a problem with the end-of-file triggering an open file
error - instead of the previous behaviour where the number of bytes in
the track header was ignored and end-of-file was checked.
I noticed this after fetching and compiling the latest simh altairz80 - it
was refusing to my mount floppy disk IMD image files (which I had made
from 8-inch floppies back in 2006).
```
maxi:s100 tony$ altairz80 cpm3bk.ini
Altair 8800 (Z80) simulator V4.0-0 Current        simh git commit id: d3f1ee09
Console escape is CTRL-\
I8272: IMD disk corrupt.
/Users/tony/s100/cpm3bk.ini-58> att disk1a0 /Users/tony/s100/C3BKSIMH.IMD
File open error
```
Looking at the commit history, I saw the change by Howard Harte to
sim_imd.c to …
> sim_imd: Check for EOF when reading IMD track headers

- sigma/sigma_bugs.txt
- sigma/sigma_mt.c
sigma_mt.c - AIO must mask unit number before calling TDV status.
> sigma: MT: AIO must mask unit number before calling TDV status.

- sigma/sigma_coc.c
Fix sigma_coc.c to return CC=0 when line has disconnected.  This problem was reported as issue #12 on kenrector/Sigma-cpv-kit concerning line hung after telnet quit.
> sigma: return corrrect CC on line disconnect

- scp.c
Currently, ```SIGTERM``` is caught and causes execution to stop, for graceful termination of a simulation. (As an example ```systemd``` by default stops a service with ```SIGTERM```.) This provides an opportunity for an ```.ini``` script to clean up. Rads are attempted from the terminal when the end of the ```.ini``` file is reached. However, there may no longer be a terminal to read from, in which case the reads will return 0 (EOF) - and will be retried forever.
If ```SIGHUP``` is defined (as it is on a *nix system), then it is configured the same as ```SIGTERM```. The apparent intent is to handle cases where this signal indicates that the process should shut down, such as the termination of a terminal session (```screen```, ```tmux```, or dialup modem hanging up :-)). However, the …
> exit on tty EOF after SIGHUP
